#!/bin/bash

export home="$HOME"
export conf="$home/projects/configuration"

# Set up symlinks
ln -sf $conf/conkyrc                  $HOME/.conkyrc
if [[ ! -d .config ]]; then mkdir .config; fi
if [[ ! -d .config/openbox ]]; then mkdir .config/openbox; fi
if [[ ! -d .config/Terminal ]]; then mkdir .config/Terminal; fi
ln -sf $conf/openbox/*                $HOME/.config/openbox/
ln -sf $conf/terminal/terminalrc      $HOME/.config/Terminal/terminalrc

ln -sf $conf/vim/vim                  $HOME/.vim
ln -sf $conf/vim/vimrc                $HOME/.vimrc
ln -sf $conf/emacs                    $HOME/.emacs

ln -sf $conf/bash/bashrc              $HOME/.bashrc
ln -sf $conf/bash/bash_profile        $HOME/.bash_profile
ln -sf $conf/bash/dir_colors          $HOME/.dir_colors
ln -sf $conf/bash/profile             $HOME/.profile
ln -sf $conf/bash/xinitrc             $HOME/.xinitrc

ln -sf $conf/git/gitconfig            $HOME/.gitconfig
ln -sf $conf/git/git-completion.bash  $home/bin/git-completion.bash

ln -sf $conf/R                        $HOME/.R
ln -sf $conf/texmf-var                $HOME/.texmf-var

rm $HOME/.vim/vim
rm $HOME/.R/R
rm $HOME/.texmf-var/texmf-var
