#!/bin/bash

export home="$HOME"
export conf="$home/projects/configuration"

# Set up symlinks
ln -sf $conf/config-arch              $HOME/.config
ln -sf $conf/conkyrc                  $HOME/.conkyrc

ln -sf $conf/vim/vim                  $HOME/.vim
ln -sf $conf/vim/vimrc                $HOME/.vimrc
ln -sf $conf/emacs                    $HOME/.emacs

ln -sf $conf/bash/bashrc              $HOME/.bashrc
ln -sf $conf/bash/bash_profile        $HOME/.bash_profile
ln -sf $conf/bash/dir_colors          $HOME/.dir_colors
ln -sf $conf/bash/profile             $HOME/.profile
ln -sf $conf/bash/xinitrc             $HOME/.xinitrc

ln -sf $conf/git/gitconfig            $HOME/.gitconfig
ln -sf $conf/git/git-completion.bash  $home/bin/git-completion.bash

ln -sf $conf/R                        $HOME/.R
ln -sf $conf/nodejs/node_modules      $HOME/.node_modules
ln -sf $conf/texmf-var                $HOME/.texmf-var

rm $HOME/.config/config-arch
rm $HOME/.vim/vim
rm $HOME/.R/R
rm $HOME/.node_modules/node_modules
rm $HOME/.texmf-var/texmf-var
