# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [[ $TERM == 'xterm' ]]; then
  export TERM='xterm-color'
fi

# Define variables
export home="$HOME"
export conf="$home/projects/configuration"
export VISUAL="/usr/bin/vim"
export EDITOR=$VISUAL

# History related settings
HISTCONTROL=ignoredups:ignorespace    # Don't put duplicate lines in the history.
shopt -s histappend                   # Append to the history file, don't overwrite it
HISTSIZE=1000
HISTFILESIZE=2000

# Source bash includes
if [[ -f "$conf/bash/includes/admin"     ]]; then source "$conf/bash/includes/admin";     fi
if [[ -f "$conf/bash/includes/aliases"   ]]; then source "$conf/bash/includes/aliases";   fi
if [[ -f "$conf/bash/includes/foraker"   ]]; then source "$conf/bash/includes/foraker";   fi
if [[ -f "$conf/bash/includes/functions" ]]; then source "$conf/bash/includes/functions"; fi
if [[ -f "$conf/bash/includes/programs"  ]]; then source "$conf/bash/includes/programs";  fi
