# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Define two very important variables
export home="$HOME"
export conf="$home/projects/configuration"

# Include user's private bin
if [[ -d "$home/bin" ]]; then PATH="$PATH:$home/bin"; fi

# Bash prompt
source "$conf/bash/prompt"

# Terminal settings
eval $(dircolors ~/.dir_colors)  # display broken symlinks
shopt -s checkwinsize  # check the window size after each command and, if necessary, update the values of LINES and COLUMNS.
export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"
export LC_CTYPE='en_US.utf-8'
export TERM='xterm-color'

# Bash history
HISTCONTROL=ignoredups:ignorespace    # Don't put duplicate lines in the history.
shopt -s histappend                   # Append to the history file, don't overwrite it
HISTSIZE=1000
HISTFILESIZE=2000

# Source bash includes
if [[ -f "$conf/bash/includes/aliases"   ]]; then source "$conf/bash/includes/aliases";   fi
if [[ -f "$conf/bash/includes/functions" ]]; then source "$conf/bash/includes/functions"; fi
if [[ -f "$conf/bash/includes/programs"  ]]; then source "$conf/bash/includes/programs";  fi

echo 'did you run yaourt -Syu today? ;)'

true
