#!/bin/bash
# Based on the marginally extensible, not very portable Bash prompt by Spencer Tipping
# WTFPL License ... cheers!

source $conf/bash/prompt-base
source $conf/bash/colors

function setup_left_and_right {
  # Your customizations go here. The idea is to export $PS1_LEFT and $PS1_RIGHT
  # as two strings, each formatted like $PS1 normally is. (That is, with \[\]
  # around escape sequences.)

  # Note that you can't use Bash-specific backslash sequences on the right; if
  # you do, this script won't know the proper length and your right prompt will
  # most likely run off the screen.

  local exit_code=$?
  local job_pid=$!

  export PS1_LEFT="$rose\h$magenta\W $text"

  #right_prompt="${cyan}($(rvm-prompt v g))${green}$(__git_ps1 "(%s)")"
  #((exit_code != 0)) && right_prompt="${magenta}(e${exit_code})${text}${right_prompt}"
  export PS1_RIGHT="$right_prompt"
}
